spring.application.name=tracker
# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL Statements in the Console (Optional)
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://financetrackerdatabase.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=dbroot
spring.datasource.password=Ailneni@1998
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================================
# MYSQL DATASOURCE CONFIGURATION
# ========================================
#spring.datasource.url=jdbc:mysql://localhost:3306/appdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true

# Enable debug logging
logging.level.org.springframework.security=DEBUG
logging.level.com.financetracker=DEBUG

#Rabbit MQ properties
#spring.rabbitmq.addresses=amqps://rblwbafy:9h2qDSM9feqGtP4AgAUEB9r1rtggCKyW@woodpecker.rmq.cloudamqp.com/rblwbafy
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#Azure
azure.servicebus.connection-string=Endpoint=sb://notify-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=amDpViuS9gVTygRwcJch/BdLFFaDt9GfB+ASbLddutU=
#azure.servicebus.connection-string=${AZURE_SERVICEBUS_CONNECTION_STRING:}
azure.servicebus.queue-name=transaction-notifications
